### ISSUE TITLE
new share button

### ISSUE THREAD

**Issue by plaidpants** [basti564/DownQuest#1]
The web site has changed. Seems to not work with the new share button instead of the previous greyed out purchase button.

**Comment by basti564** [comment]
Hey, I think this hasn't been caused by the new share button, but by "/" at the end of the URL
I fixed it in commit 25b6d7475aa429de12471e82a69b00ff7901e523 and release v1.3.1

**Comment by plaidpants** [comment]
Works now, thanks.
