### ISSUE TITLE
Seriously Meta?.

### ISSUE THREAD

**Issue by ChromiaCat** [basti564/DownQuest#11]
Could you please update both to indicate that third party cookies are required for DownQ to work?
I was about to make an issue about DownQ not being able to generate the required download links but all it needed is to allow meta.com to use third party cookies.
Some users might not think that's what they need to do if they have third party cookie blocking enabled(like me) and explaining this in both the repo's readme & the store listing might help some people.

**Comment by Vojtak42** [comment]
It didn't help for me.

**Comment by ChromiaCat** [comment]
> It didn't help for me.

What's your issue?

**Comment by Vojtak42** [comment]
It can't generate all the required download links.

**Comment by ChromiaCat** [comment]
> It can't generate all the required download links.

Try to do step 6 before 1 if you didn't do that already.

**Comment by Vojtak42** [comment]
I have already tried this.

**Comment by ChromiaCat** [comment]
> I have already tried this.

If you use Chrome (and you have the "Block third-party cookies" option on), go to Privacy & Security > Third-party Cookies and see if at the bottom there's a rule for meta.com, it should be [*.]meta.com 
![image](https://github.com/basti564/DownQuest/assets/43613021/5a1b1bce-668b-452b-af12-40e82e60d20b)

If you use another browser I don't know how to help.

**Comment by ChromiaCat** [comment]
Wait now it doesn't work for me as well...
@basti564 Did Meta change something again?

**Comment by ChromiaCat** [comment]
Nevermind, not even ComputerElite's downloader works. 

Seems Meta changed something about their authentication method.

**Comment by basti564** [comment]
Closing this as DownQuest has been fixed as of https://github.com/basti564/DownQuest/releases/tag/v1.5.0
It might take a while for the update to be listed on the Edge or Chrome store tho
