### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by petermg** [basti564/DownQuest#2]
Doesn't seem to work at ALL on EDGE, don't get the downgrade option... and in Chrome when I select anything to download it tells me
TypeError: Cannot convert undefined or null to object

**Comment by basti564** [comment]
It still works for me in both browsers.
Are you sure that TypeError is caused by DownQuest?
Can you please link me to the app you're trying this with and send your complete browser console output for both Chrome and Edge?
Thanks!
