### ISSUE TITLE
No downloaded apps will run

### ISSUE THREAD

**Issue by JadeTank** [basti564/DownQuest#3]
Apologies if I'm just missing something here, but none of the downloaded apps will run once sideloaded. They will all start up briefly, then immediately crash to the home screen. 

For context, I am also using Oculess, but I don't know how this all well enough to know if its causing this issue.

**Comment by basti564** [comment]
> For context, I am also using Oculess
Did you just disable telemetry with Oculess or did you remove your whole account. Games downloaded with DownQuest from the store won't run without an account or a patch.

**Comment by JadeTank** [comment]
I did remove the account. Do you know of a patch can be applied? If not, I'll probably just need to reset it and not remove the account next time.

**Comment by basti564** [comment]
> I did remove the account. Do you know of a patch can be applied? If not, I'll probably just need to reset it and not remove the account next time.

Ah, that's the problem, I'm legally not allowed to patch the app because it would enable piracy, I'm sorry.
You actually don't need to reset your Quest to get your account back. Just pairing the Quest with the Phone App should be enough to get it back.

**Comment by JadeTank** [comment]
Gotcha, makes sense. Though, the only ones I want are the free ones ironically. Thanks for the info and reply, I'll probably reconnect the account that way.
