### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by bhdgsk** [basti564/DownQuest#4]
Now before I say anything, I did download a quest 2 game onto a Quest 1. Bet set that aside, as there is no audio. The game runs okay and is playable. The game in question is Green Hell VR. I sideloaded the APK and the .obb file. There was a couple of other files called ____.bundle, but I did not know what to do with those. What should I do?

**Comment by basti564** [comment]
Try to put the bundle files into the same folder where you put the obb file. Let me know if that works.
(I'm closing this issue because it's unrelated to DownQuest)

**Comment by bhdgsk** [comment]
It did work!
