### ISSUE TITLE
Unsupported compress method

### ISSUE THREAD

**Issue by xAstroBoy** [basti564/DownQuest#5]
Trying to download this game 
https://www.oculus.com/experiences/rift/1011429558899116

Before the microtransaction update, basically having the good game, but downquest gives error 

![image](https://user-images.githubusercontent.com/92211398/186990657-26e50034-926e-4702-bd92-434ba5e0383a.png)

![image](https://user-images.githubusercontent.com/92211398/186990701-d3aca942-aeac-4d51-96e7-29be66d8e888.png)

**Comment by basti564** [comment]
Hi @xAstroBoy,
it seems like parts of the Fishing/Content/Paks/Fishing.pak file have been deleted from the oculus server so you won't be able to downgrade to that version.
I'll see if I can improve error messages to reflect the actual root cause in the future.
