### ISSUE TITLE
this extension works on some games and apps but some give me error :cannot convert undefined or null to object ...

### ISSUE THREAD

**Issue by 2jkaz** [basti564/DownQuest#7]
i found out if i directly download files from their web theres two different types of errors

1.file starts downloading and then cuts at certain percentage then Network error - not sure if the problem is with corrupted data or server itself

2.upon reaching the targeted file i get error: Cannot convert undefined or null to object - not sure if the file is missing or path to this file is not accurate or the downloader cannot make sense of the target...any chance u could check the error?

**Comment by basti564** [comment]
Hey, can you please link me to the item.
It's very likely that part of it just got deleted of oculuscdn meaning that it can't be downloaded anymore

**Comment by 2jkaz** [comment]
https://www.oculus.com/experiences/gear-vr/992503684170594/

**Comment by di2ger** [comment]
The same issue here:
https://www.oculus.com/experiences/go/1284669471561141/

**Comment by basti564** [comment]
It seams like oculus cdn is deleting parts of old downloads, which causes it to only download parts of the files. I don't think I can do anything about this

**Comment by di2ger** [comment]
Such a bad service...
Do you know if it's possible to switch to some of their mirrors? I tried VPN without success.

**Comment by 2jkaz** [comment]
> It seams like oculus cdn is deleting parts of old downloads, which causes it to only download parts of the files. I don't think I can do anything about this

Thank you for trying to look at it really appreciate your work on DownQuest...

**Comment by 2jkaz** [comment]
> Such a bad service...
> Do you know if it's possible to switch to some of their mirrors? I tried VPN without success.

Only way to get these files now  is to get them from other people's backups...
