### ISSUE TITLE
app signing issues on Go

### ISSUE THREAD

**Issue by bmilliron67** [basti564/DownQuest#8]
If I use the browser extension to download Go apps and then sideload them they show up under "Unknown Sources" and hang or crash on the load screen. If I use the built in Store app to "purchase" the app first (for free apps also) then sideload the apk it shows up under the Apps tab in Library and loads fine. So it seems there is some issue with the app signing unless the app is already registered in the device. FYI

**Comment by basti564** [comment]
It's an anti piracy protection, I can't do anything about that.
