### ISSUE TITLE
Change Site Access match from Oculus to Meta

### ISSUE THREAD

**Issue by ChromiaCat** [basti564/DownQuest#9]
Since Oculus is owned by Meta, https://www.oculus.com/experiences/quest/  redirects to https://www.meta.com/experiences/
as well as store entries.

Deeper changes aside from site access match might be needed but I'm not sure.

**Comment by oxygenvl** [comment]
I tried editing the code but I'm not sure what API's Facebook has changed the domain of. I can't seem to get this to work.

**Comment by ChromiaCat** [comment]
Ah, I forgot the API URL needs to change as well.
Maybe if you initiate a download from the Oculus client and monitor the IPs/domains it connects to?

**Comment by Junior-Michael** [comment]
:(

**Comment by basti564** [comment]
I fixed this in d35cc19. It should be on the chrome extension store soon :)
